import RestaurantCard from "../RestaurantCard/RestaurantCard";
import "./Card.css";

const resObj = {
  data: {
    type: "F",
    id: "41890",
    name: "Al Jawahar Restaurant (Jama Masjid)",
    uuid: "f9d26830-a7ee-4d59-9b9c-fdb3ccd310d9",
    city: "4",
    area: "NEAR JAMA MASJID",
    totalRatingsString: "1000+ ratings",
    cloudinaryImageId: "l2hcl3u2g1cdgkz6kdd2",
    cuisines: ["Mughlai", "North Indian"],
    tags: [],
    costForTwo: 40000,
    costForTwoString: "₹400 FOR TWO",
    deliveryTime: 48,
    minDeliveryTime: 48,
    maxDeliveryTime: 48,
    slaString: "48 MINS",
    lastMileTravel: 2.4000000953674316,
    slugs: {
      restaurant: "al-jawahar-jama-masjid-old-delhi",
      city: "delhi",
    },
    cityState: "4",
    address: "8-15,JAMA MASJID BAZAR,MATIA MAHAL",
    locality: "NEAR JAMA MASJID",
    parentId: 16637,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    ribbon: [
      {
        type: "PROMOTED",
      },
    ],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "special",
          fee: 2000,
          message: "",
        },
        {
          name: "distance",
          fee: 3200,
          message: "",
        },
        {
          name: "time",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5200,
      message: "",
      title: "Delivery Charge",
      amount: "5200",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "LIGHT",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID:
      "cid=7423483~p=1~eid=00000189-39d6-daca-0b31-c59800cc0174~srvts=1688892529354",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.4 kms",
    hasSurge: false,
    sla: {
      restaurantId: "41890",
      deliveryTime: 48,
      minDeliveryTime: 48,
      maxDeliveryTime: 48,
      lastMileTravel: 2.4000000953674316,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "LIGHT",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: true,
    avgRating: "3.5",
    totalRatings: 1000,
    new: false,
  },
  subtype: "basic",
  crouton: {
    type: "RAIN",
    metaInfo: {
      bgColor: "#282C3F",
      icon: "surge_listing_piuzrv",
      textColor: "#ffffff",
      title: "Bad Weather",
      message: "₹20 extra levied on some restaurants",
    },
  },
};

const resList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "41890",
      name: "Al Jawahar Restaurant (Jama Masjid)",
      uuid: "f9d26830-a7ee-4d59-9b9c-fdb3ccd310d9",
      city: "4",
      area: "NEAR JAMA MASJID",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "l2hcl3u2g1cdgkz6kdd2",
      cuisines: ["Mughlai", "North Indian"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 48,
      minDeliveryTime: 48,
      maxDeliveryTime: 48,
      slaString: "48 MINS",
      lastMileTravel: 2.4000000953674316,
      slugs: {
        restaurant: "al-jawahar-jama-masjid-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "8-15,JAMA MASJID BAZAR,MATIA MAHAL",
      locality: "NEAR JAMA MASJID",
      parentId: 16637,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7423483~p=1~eid=00000189-39d6-daca-0b31-c59800cc0174~srvts=1688892529354",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.4 kms",
      hasSurge: false,
      sla: {
        restaurantId: "41890",
        deliveryTime: 48,
        minDeliveryTime: 48,
        maxDeliveryTime: 48,
        lastMileTravel: 2.4000000953674316,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.5",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "395433",
      name: "Bikanervala Chandni Chowk",
      uuid: "896fae8d-90ec-447d-89db-a7591fab5e28",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "puzcg8zkqg5vus1prtob",
      cuisines: ["Street Food", "Sweets"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "bikanervala-–-chandni-chowk-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "382, NEAR FATEH PUR, CHANDNI CHOWK,110006",
      locality: "Fatehpuri",
      parentId: 242230,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      sla: {
        restaurantId: "395433",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "598217",
      name: "Chaina Ram Sindhi Halwai",
      uuid: "92eb265a-08dc-46f7-a1f6-8780d56736fc",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "a9k2qxr4dojc77dzdxug",
      cuisines: ["Sweets", "Snacks"],
      tags: [],
      costForTwo: 70000,
      costForTwoString: "₹700 FOR TWO",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: "23 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "chaina-ram-sindhi-halwai-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "6499, Fatehpuri Chowk, Central delhi- 110006",
      locality: "Chandni Chowk Road",
      parentId: 57265,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "598217",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.5",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "193479",
      name: "Haldiram's",
      uuid: "69ffdd4a-d18a-46f5-ace3-36f22dd13b60",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "hnxwug8pbnby5ftshubz",
      cuisines: ["Sweets", "Snacks", "North Indian"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 34,
      minDeliveryTime: 34,
      maxDeliveryTime: 34,
      slaString: "34 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "haldiram's-connaught-place-connaught-place-2",
        city: "delhi",
      },
      cityState: "4",
      address: "1452/2 Near Fountain Chandni Chowk Delhi 110015",
      locality: "Kucha Mahajani",
      parentId: 377669,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      sla: {
        restaurantId: "193479",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "52649",
      name: "Soni Bhojnalaya",
      uuid: "f56028a2-1aec-4fda-b53e-fd17b7e9bd44",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "ttsewpica42m7hxip64c",
      cuisines: ["North Indian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 41,
      minDeliveryTime: 41,
      maxDeliveryTime: 41,
      slaString: "41 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "soni-bhojnalaya-chandni-chowk-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "161, Kucha Ghasi Ram, Fatehpuri, Chandni Chowk, New Delhi",
      locality: "Chandni Chowk",
      parentId: 190945,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "52649",
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "592610",
      name: "Adarsh Vegetarian",
      uuid: "531d5693-a28f-4713-aa92-2dcb43e9e388",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "kyq00hgqi7qkjxzs19lr",
      cuisines: ["North Indian", "Tandoor", "Snacks"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 38,
      minDeliveryTime: 38,
      maxDeliveryTime: 38,
      slaString: "38 MINS",
      lastMileTravel: 0.8999999761581421,
      slugs: {
        restaurant: "adarsh-vegetarian-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address:
        "482-483, Haveli Haider Kuli, Chandni Chowk, New Delhi, Delhi 110006, India",
      locality: "Haveli Haider Kuli",
      parentId: 26983,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "592610",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        lastMileTravel: 0.8999999761581421,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "67389",
      name: "Capten Milkshakes",
      uuid: "ec538c3a-e1ae-4102-96eb-919beff7356c",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "vcgdylocyora1n2m1vql",
      cuisines: ["Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 1.2999999523162842,
      slugs: {
        restaurant: "capten-milkshakes-chandni-chowk-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address:
        "1215, Main Chandni Chowk Road, Opposite New Katra, Chandni Chowk, New Delhi",
      locality: "Maliwara",
      parentId: 55872,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      sla: {
        restaurantId: "67389",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 1.2999999523162842,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "41975",
      name: "Al Yousuf",
      uuid: "799ad189-ec50-4a85-8b17-92cfeabb16da",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "dsq8nni8c5zy0bnirfha",
      cuisines: ["Mughlai"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "al-yousuf-chandni-chowk-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "5187, Ballimaran, Chandni Chowk, New Delhi",
      locality: "Ballimaran Road",
      parentId: 29524,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      sla: {
        restaurantId: "41975",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.0",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "41653",
      name: "The Brijwasi Restaurant",
      uuid: "06e03e3f-7362-4eae-9182-9fa7da167448",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "ttroo3iyayg1vdrytlj0",
      cuisines: ["North Indian", "South Indian", "Continental", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 44,
      minDeliveryTime: 44,
      maxDeliveryTime: 44,
      slaString: "44 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "brijwasi-restaurant-chandni-chowk-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "379, Near Kucha Ghasi Ram, Chandni Chowk, New Delhi",
      locality: "Kucha Ghasiram",
      parentId: 205857,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      sla: {
        restaurantId: "41653",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "41648",
      name: "Jung Bahadur Kachori Wala (Old Delhi Original)",
      uuid: "0f737f43-0799-41e0-8fca-68d9ff7fd2fb",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "qokddzim0w19rz6heik3",
      cuisines: ["Snacks"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 1.600000023841858,
      slugs: {
        restaurant: "jung-bahadur-kachori-wala-chandni-chowk-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "1104, Maliwara Jogiwari, Gali Paranthe Wali",
      locality: "Jogiwari Road",
      parentId: 112168,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.6 kms",
      hasSurge: false,
      sla: {
        restaurantId: "41648",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 1.600000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "287303",
      name: "Jain Snacks Corner",
      uuid: "678536c8-5986-4a68-a7f0-e5ee448337a3",
      city: "4",
      area: "Chandni Chowk",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "qoeckrn2ltvzohxlc5v8",
      cuisines: ["Indian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 1.5,
      slugs: {
        restaurant: "jain-snacks-corner-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "1472 FOUNTAIN,CHANDNI CHOWK,DELHI",
      locality: "Kucha Mahajani",
      parentId: 108993,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "287303",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 1.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "705497",
      name: "Wah ji wah",
      uuid: "af867350-f201-4dcf-ad39-91dea462b06c",
      city: "4",
      area: "Old Delhi",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "a60e34d3e4ee77c2a2b264a6a6bf69bd",
      cuisines: ["Chinese", "Indian", "South Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 41,
      minDeliveryTime: 41,
      maxDeliveryTime: 41,
      slaString: "41 MINS",
      lastMileTravel: 1.7000000476837158,
      slugs: {
        restaurant: "wah-ji-wah-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "SHOP NO 1908, CHANDNI CHOWK DELHI-110006",
      locality: "Chandni Chowk",
      parentId: 966,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.7 kms",
      hasSurge: false,
      sla: {
        restaurantId: "705497",
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        lastMileTravel: 1.7000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "41658",
      name: "Standard Sweets",
      uuid: "d0627e12-05d7-4fb7-a502-41f926e91508",
      city: "4",
      area: "Chawri Bazar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "gatrugxqrazdahmr39c4",
      cuisines: ["Sweets", "Snacks"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 2,
      slugs: {
        restaurant: "standard-sweets-chawri-bazar-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address: "3510, Chawri Bazar, New Delhi",
      locality: "Hakim Baka Street",
      parentId: 195284,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2 kms",
      hasSurge: false,
      sla: {
        restaurantId: "41658",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 2,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "624320",
      name: "Taufiq Dilpasand Biryani Point",
      uuid: "f204df9f-519e-4803-b2db-182c81d29594",
      city: "4",
      area: "Jama Masjid",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "jcqnx2vire2klolzkqx8",
      cuisines: ["Biryani"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: "29 MINS",
      lastMileTravel: 2.700000047683716,
      slugs: {
        restaurant: "taufiq-dilpasand-biryani-point-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address:
        "735 A G/F Gali Haveli Azam Khan, Bazar Chitli Qabar, Jama Masjid, Chandni Chowk, Delhi",
      locality: "Bazar Chitli Qabar",
      parentId: 371388,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "LIGHT",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.7 kms",
      hasSurge: false,
      sla: {
        restaurantId: "624320",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 2.700000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "LIGHT",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "590736",
      name: "SR Bakery",
      uuid: "48dc6719-dfcf-4ba8-b8a2-a40562c2ed7a",
      city: "4",
      area: "Karol Bagh",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "bzn2n1zygynviqnjshc7",
      cuisines: ["Bakery"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 31,
      minDeliveryTime: 31,
      maxDeliveryTime: 31,
      slaString: "31 MINS",
      lastMileTravel: 1.399999976158142,
      slugs: {
        restaurant: "sai-ramesh-bakery-old-delhi-old-delhi",
        city: "delhi",
      },
      cityState: "4",
      address:
        "House no. 268, 1st floor, gali-kucha sanjogi ram, naya bans, khari baoli, Delhi-6",
      locality: "Naya Bans Rd",
      parentId: 192975,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "special",
            fee: 2000,
            message: "",
          },
          {
            name: "distance",
            fee: 3200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "HEAVY",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "590736",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        lastMileTravel: 1.399999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "HEAVY",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "RAIN",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "Bad Weather",
        message: "₹20 extra levied on some restaurants",
      },
    },
  },
];

//  not using keys (not acceptable) <<< index as key <<<<<<<< uniques id  (best practice)

const Card = () => {
  return (
    <div className="card-body">
      <div className="search">
        <input type="text" placeholder = "search..." />
      </div>
      <div className="card-container">
        {/* key is reserve keyword */}
        {resList.map((restaurant) => (
          <RestaurantCard key={restaurant.data.id} resData={restaurant} />
        ))}
      </div>
    </div>
  );
};
export default Card;
